-- MySQL Script generated by MySQL Workbench
-- Wed Dec 20 13:37:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema IsDb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema IsDb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `IsDb` DEFAULT CHARACTER SET utf8 ;
USE `IsDb` ;

-- -----------------------------------------------------
-- Table `IsDb`.`ExecutorProfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IsDb`.`ExecutorProfile` (
  `idExecutorProfile` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(15) NOT NULL,
  `PasswordHash` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idExecutorProfile`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IsDb`.`CustomerProfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IsDb`.`CustomerProfile` (
  `idCustomerProfile` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `PhoneNumber` VARCHAR(45) NOT NULL,
  `PasswordHash` VARCHAR(45) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCustomerProfile`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IsDb`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IsDb`.`Customer` (
  `idCustomer` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Contact` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCustomer`),
  CONSTRAINT `CustomerUser`
    FOREIGN KEY (`idCustomer`)
    REFERENCES `IsDb`.`CustomerProfile` (`idCustomerProfile`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IsDb`.`Car`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IsDb`.`Car` (
  `idCar` INT NOT NULL AUTO_INCREMENT,
  `Brand` VARCHAR(45) NOT NULL,
  `Model` VARCHAR(45) NOT NULL,
  `YearOfRelease` VARCHAR(45) NOT NULL,
  `LicensePlateNumber` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IsDb`.`Executor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IsDb`.`Executor` (
  `idExecutor` INT NOT NULL,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Contact` VARCHAR(45) NOT NULL,
  `CarID` INT NULL,
  `DepartureDate` DATETIME NULL,
  PRIMARY KEY (`idExecutor`),
  INDEX `car_idx` (`CarID` ASC) VISIBLE,
  CONSTRAINT `id`
    FOREIGN KEY (`idExecutor`)
    REFERENCES `IsDb`.`ExecutorProfile` (`idExecutorProfile`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `car`
    FOREIGN KEY (`CarID`)
    REFERENCES `IsDb`.`Car` (`idCar`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IsDb`.`Order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IsDb`.`Order` (
  `idOrder` INT NOT NULL AUTO_INCREMENT,
  `customersID` INT NOT NULL,
  `performersID` INT NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `cost` FLOAT NOT NULL,
  `dateOrder` DATETIME NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idOrder`),
  INDEX `CustomersID_idx` (`customersID` ASC) VISIBLE,
  INDEX `executorID_idx` (`performersID` ASC) VISIBLE,
  CONSTRAINT `CustomersID`
    FOREIGN KEY (`customersID`)
    REFERENCES `IsDb`.`Customer` (`idCustomer`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `executorID`
    FOREIGN KEY (`performersID`)
    REFERENCES `IsDb`.`Executor` (`idExecutor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `IsDb`.`financialAccounting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `IsDb`.`financialAccounting` (
  `RecordID` INT NOT NULL AUTO_INCREMENT,
  `OrderID` INT NOT NULL,
  `OrderCost` FLOAT NOT NULL,
  `OrderDate` DATETIME NOT NULL,
  PRIMARY KEY (`RecordID`),
  INDEX `order_idx` (`OrderID` ASC) VISIBLE,
  CONSTRAINT `order`
    FOREIGN KEY (`OrderID`)
    REFERENCES `IsDb`.`Order` (`idOrder`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
